name: Connectivity Test

on:
  push:
    branches: [ connectivity-test ]
  workflow_dispatch:

jobs:
  check-api:
    runs-on: [self-hosted-linux-amd64-noble-xlarge]

    steps:
      - name: Test Connectivity
        run: |
          echo "Testing connection"
          # -I: Fetch headers only
          # -s: Silent mode
          # -S: Show errors if it fails
          # -L: Follow redirects
          curl -k -IsS -L https://security-vm-scanning-batch.internal --connect-timeout 30
